id: I01C59797
ocr_import_info:
  timestamp: '2023-09-28T04:49:42.933278+00:00'
  batch_id: batch-eb04
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-28 15:04:14.945746+00:00
last_modified: 2023-09-28 15:04:14.945754+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ1272
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ1272
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཕུང་པོ་ལྔའི་འགྲེལ་བཤད།
  languages:
  - bo
  author: བླ་བན་ཆོས་ཀྱི་བརྩོན་འགྲུས།
statistics:
  ocr_word_mean_confidence_index: 0.8498570067897363
  ocr_word_median_confidence_index: 0.8938438
bases:
  I1CZ1765:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ1765
      total_pages: 92
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ1765.txt
    statistics:
      ocr_word_median_confidence_index: 0.8938438
      ocr_word_mean_confidence_index: 0.8498570067897363
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
